//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novell.Directory.Ldap.Utilclass {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novell.Directory.Ldap.Utilclass.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot bind. Use PoolManager.getBoundConnection().
        /// </summary>
        public static string CANNOT_BIND {
            get {
                return ResourceManager.GetString("CANNOT_BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection closed by the application disconnecting.
        /// </summary>
        public static string CONNECTION_CLOSED {
            get {
                return ResourceManager.GetString("CONNECTION_CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to connect to server {0}:{1}.
        /// </summary>
        public static string CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("CONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection closed by the application finalizing the object.
        /// </summary>
        public static string CONNECTION_FINALIZED {
            get {
                return ResourceManager.GetString("CONNECTION_FINALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to reconnect to server, application has never called connect().
        /// </summary>
        public static string CONNECTION_IMPOSSIBLE {
            get {
                return ResourceManager.GetString("CONNECTION_IMPOSSIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reader thread terminated.
        /// </summary>
        public static string CONNECTION_READER {
            get {
                return ResourceManager.GetString("CONNECTION_READER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connection lost waiting for results from {0}:{1}.
        /// </summary>
        public static string CONNECTION_WAIT {
            get {
                return ResourceManager.GetString("CONNECTION_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Decoding responseValue.
        /// </summary>
        public static string DECODING_ERROR {
            get {
                return ResourceManager.GetString("DECODING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid DN parameter.
        /// </summary>
        public static string DN_PARAM_ERROR {
            get {
                return ResourceManager.GetString("DN_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RfcLdapMessage: Cannot duplicate message built from the input stream.
        /// </summary>
        public static string DUP_ERROR {
            get {
                return ResourceManager.GetString("DUP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encoding Error.
        /// </summary>
        public static string ENCODING_ERROR {
            get {
                return ResourceManager.GetString("ENCODING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Entry parameter.
        /// </summary>
        public static string ENTRY_PARAM_ERROR {
            get {
                return ResourceManager.GetString("ENTRY_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expecting left parenthesis, found &quot;{0}&quot;.
        /// </summary>
        public static string EXPECTING_LEFT_PAREN {
            get {
                return ResourceManager.GetString("EXPECTING_LEFT_PAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expecting right parenthesis, found &quot;{0}&quot;.
        /// </summary>
        public static string EXPECTING_RIGHT_PAREN {
            get {
                return ResourceManager.GetString("EXPECTING_RIGHT_PAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: Failed Referral: {1}.
        /// </summary>
        public static string FAILED_REFERRAL {
            get {
                return ResourceManager.GetString("FAILED_REFERRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referral not supported for command {0}.
        /// </summary>
        public static string IMPROPER_REFERRAL {
            get {
                return ResourceManager.GetString("IMPROPER_REFERRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid syntax for address with port; {0}.
        /// </summary>
        public static string INVALID_ADDRESS {
            get {
                return ResourceManager.GetString("INVALID_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid character &quot;{0}&quot; in attribute description.
        /// </summary>
        public static string INVALID_CHAR_IN_DESCR {
            get {
                return ResourceManager.GetString("INVALID_CHAR_IN_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The invalid character &quot;{0}&quot; needs to be escaped as &quot;{1}&quot;.
        /// </summary>
        public static string INVALID_CHAR_IN_FILTER {
            get {
                return ResourceManager.GetString("INVALID_CHAR_IN_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escape sequence not allowed in attribute description.
        /// </summary>
        public static string INVALID_ESC_IN_DESCR {
            get {
                return ResourceManager.GetString("INVALID_ESC_IN_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid value in escape sequence &quot;{0}&quot;.
        /// </summary>
        public static string INVALID_ESCAPE {
            get {
                return ResourceManager.GetString("INVALID_ESCAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid comparison operator.
        /// </summary>
        public static string INVALID_FILTER_COMPARISON {
            get {
                return ResourceManager.GetString("INVALID_FILTER_COMPARISON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I/O Exception on host {0}, port {1}.
        /// </summary>
        public static string IO_EXCEPTION {
            get {
                return ResourceManager.GetString("IO_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: Matched DN: {1}.
        /// </summary>
        public static string MATCHED_DN {
            get {
                return ResourceManager.GetString("MATCHED_DN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unmatched parentheses, left parenthesis missing.
        /// </summary>
        public static string MISSING_LEFT_PAREN {
            get {
                return ResourceManager.GetString("MISSING_LEFT_PAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unmatched parentheses, right parenthesis missing.
        /// </summary>
        public static string MISSING_RIGHT_PAREN {
            get {
                return ResourceManager.GetString("MISSING_RIGHT_PAREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiple schema found when reading the subschemaSubentry for {0}.
        /// </summary>
        public static string MULTIPLE_SCHEMA {
            get {
                return ResourceManager.GetString("MULTIPLE_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing attribute description.
        /// </summary>
        public static string NO_ATTRIBUTE_NAME {
            get {
                return ResourceManager.GetString("NO_ATTRIBUTE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DN and matching rule not specified.
        /// </summary>
        public static string NO_DN_NOR_MATCHING_RULE {
            get {
                return ResourceManager.GetString("NO_DN_NOR_MATCHING_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot duplicate message to follow referral for {0} request, not allowed.
        /// </summary>
        public static string NO_DUP_REQUEST {
            get {
                return ResourceManager.GetString("NO_DUP_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Missing matching rule.
        /// </summary>
        public static string NO_MATCHING_RULE {
            get {
                return ResourceManager.GetString("NO_MATCHING_RULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All results could not be stored in memory, sort failed.
        /// </summary>
        public static string NO_MEMORY {
            get {
                return ResourceManager.GetString("NO_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Semicolon present, but no option specified.
        /// </summary>
        public static string NO_OPTION {
            get {
                return ResourceManager.GetString("NO_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No schema found when reading the subschemaSubentry for {0}.
        /// </summary>
        public static string NO_SCHEMA {
            get {
                return ResourceManager.GetString("NO_SCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An attempt to stopTLS on a connection where startTLS had not been called.
        /// </summary>
        public static string NO_STARTTLS {
            get {
                return ResourceManager.GetString("NO_STARTTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Requested property is not supported..
        /// </summary>
        public static string NO_SUP_PROPERTY {
            get {
                return ResourceManager.GetString("NO_SUP_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StartTLS failed because no LdapTLSSocketFactory has been set for this Connection.
        /// </summary>
        public static string NO_TLS_FACTORY {
            get {
                return ResourceManager.GetString("NO_TLS_FACTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schema element is not an LdapAttributeSchema object.
        /// </summary>
        public static string NOT_AN_ATTRIBUTE {
            get {
                return ResourceManager.GetString("NOT_AN_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Method LdapConnection.startTLS not implemented.
        /// </summary>
        public static string NOT_IMPLEMENTED {
            get {
                return ResourceManager.GetString("NOT_IMPLEMENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid extended operation parameter, no OID specified.
        /// </summary>
        public static string OP_PARAM_ERROR {
            get {
                return ResourceManager.GetString("OP_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot start or stop TLS because outstanding Ldap operations exist on this connection.
        /// </summary>
        public static string OUTSTANDING_OPERATIONS {
            get {
                return ResourceManager.GetString("OUTSTANDING_OPERATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid parameter.
        /// </summary>
        public static string PARAM_ERROR {
            get {
                return ResourceManager.GetString("PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid DN or RDN parameter.
        /// </summary>
        public static string RDN_PARAM_ERROR {
            get {
                return ResourceManager.GetString("RDN_PARAM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read response is ambiguous, multiple entries returned.
        /// </summary>
        public static string READ_MULTIPLE {
            get {
                return ResourceManager.GetString("READ_MULTIPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error attempting to follow a search continuation reference.
        /// </summary>
        public static string REFERENCE_ERROR {
            get {
                return ResourceManager.GetString("REFERENCE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search result reference received, and referral following is off.
        /// </summary>
        public static string REFERENCE_NOFOLLOW {
            get {
                return ResourceManager.GetString("REFERENCE_NOFOLLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LdapBind.bind() function returned null.
        /// </summary>
        public static string REFERRAL_BIND {
            get {
                return ResourceManager.GetString("REFERRAL_BIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Could not match LdapBind.bind() connection with Server Referral URL list.
        /// </summary>
        public static string REFERRAL_BIND_MATCH {
            get {
                return ResourceManager.GetString("REFERRAL_BIND_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error attempting to follow a referral.
        /// </summary>
        public static string REFERRAL_ERROR {
            get {
                return ResourceManager.GetString("REFERRAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: Referral: {1}.
        /// </summary>
        public static string REFERRAL_ITEM {
            get {
                return ResourceManager.GetString("REFERRAL_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LdapSearchResults.{0}(): No entry found &amp; request is not complete.
        /// </summary>
        public static string REFERRAL_LOCAL {
            get {
                return ResourceManager.GetString("REFERRAL_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error sending request to referred server.
        /// </summary>
        public static string REFERRAL_SEND {
            get {
                return ResourceManager.GetString("REFERRAL_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error connecting to server {0} while attempting to follow a referral.
        /// </summary>
        public static string SERVER_CONNECT_ERROR {
            get {
                return ResourceManager.GetString("SERVER_CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: Server Message: {1}.
        /// </summary>
        public static string SERVER_MSG {
            get {
                return ResourceManager.GetString("SERVER_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Received unsolicited notification from server {0}:{1} to shutdown.
        /// </summary>
        public static string SERVER_SHUTDOWN_REQ {
            get {
                return ResourceManager.GetString("SERVER_SHUTDOWN_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incomplete escape sequence.
        /// </summary>
        public static string SHORT_ESCAPE {
            get {
                return ResourceManager.GetString("SHORT_ESCAPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please ensure that SSL Provider is properly installed..
        /// </summary>
        public static string SSL_PROVIDER_MISSING {
            get {
                return ResourceManager.GetString("SSL_PROVIDER_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error stopping TLS: Error getting input &amp; output streams from the original socket.
        /// </summary>
        public static string STOPTLS_ERROR {
            get {
                return ResourceManager.GetString("STOPTLS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}: {1} ({2}) {3}.
        /// </summary>
        public static string TOSTRING {
            get {
                return ResourceManager.GetString("TOSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Length of attribute Name array does not equal length of Flags array.
        /// </summary>
        public static string UNEQUAL_LENGTHS {
            get {
                return ResourceManager.GetString("UNEQUAL_LENGTHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unexpected end of filter.
        /// </summary>
        public static string UNEXPECTED_END {
            get {
                return ResourceManager.GetString("UNEXPECTED_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown Ldap result code {0}.
        /// </summary>
        public static string UNKNOWN_RESULT {
            get {
                return ResourceManager.GetString("UNKNOWN_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StartTLS cannot use the set socket factory because it does not implement LdapTLSSocketFactory.
        /// </summary>
        public static string WRONG_FACTORY {
            get {
                return ResourceManager.GetString("WRONG_FACTORY", resourceCulture);
            }
        }
    }
}
