//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novell.Directory.Ldap.Utilclass {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResultCodeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultCodeMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novell.Directory.Ldap.Utilclass.ResultCodeMessages", typeof(ResultCodeMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operations Error.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referral.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrative Limit Exceeded.
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TLS not supported.
        /// </summary>
        public static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SSL handshake failed.
        /// </summary>
        public static string _113 {
            get {
                return ResourceManager.GetString("113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SSL Provider not found.
        /// </summary>
        public static string _114 {
            get {
                return ResourceManager.GetString("114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unavailable Critical Extension.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confidentiality Required.
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SASL Bind In Progress.
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Such Attribute.
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undefined Attribute Type.
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inappropriate Matching.
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constraint Violation.
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protocol Error.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attribute Or Value Exists.
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Attribute Syntax.
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timelimit Exceeded.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Such Object.
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias Problem.
        /// </summary>
        public static string _33 {
            get {
                return ResourceManager.GetString("33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid DN Syntax.
        /// </summary>
        public static string _34 {
            get {
                return ResourceManager.GetString("34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Is Leaf.
        /// </summary>
        public static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alias Dereferencing Problem.
        /// </summary>
        public static string _36 {
            get {
                return ResourceManager.GetString("36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sizelimit Exceeded.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inappropriate Authentication.
        /// </summary>
        public static string _48 {
            get {
                return ResourceManager.GetString("48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid Credentials.
        /// </summary>
        public static string _49 {
            get {
                return ResourceManager.GetString("49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compare False.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insufficient Access Rights.
        /// </summary>
        public static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busy.
        /// </summary>
        public static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unavailable.
        /// </summary>
        public static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unwilling To Perform.
        /// </summary>
        public static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loop Detect.
        /// </summary>
        public static string _54 {
            get {
                return ResourceManager.GetString("54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compare True.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Naming Violation.
        /// </summary>
        public static string _64 {
            get {
                return ResourceManager.GetString("64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object Class Violation.
        /// </summary>
        public static string _65 {
            get {
                return ResourceManager.GetString("65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Allowed On Non-leaf.
        /// </summary>
        public static string _66 {
            get {
                return ResourceManager.GetString("66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not Allowed On RDN.
        /// </summary>
        public static string _67 {
            get {
                return ResourceManager.GetString("67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entry Already Exists.
        /// </summary>
        public static string _68 {
            get {
                return ResourceManager.GetString("68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object Class Modifications Prohibited.
        /// </summary>
        public static string _69 {
            get {
                return ResourceManager.GetString("69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authentication Method Not Supported.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Affects Multiple DSAs.
        /// </summary>
        public static string _71 {
            get {
                return ResourceManager.GetString("71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strong Authentication Required.
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Other.
        /// </summary>
        public static string _80 {
            get {
                return ResourceManager.GetString("80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server Down.
        /// </summary>
        public static string _81 {
            get {
                return ResourceManager.GetString("81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local Error.
        /// </summary>
        public static string _82 {
            get {
                return ResourceManager.GetString("82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encoding Error.
        /// </summary>
        public static string _83 {
            get {
                return ResourceManager.GetString("83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decoding Error.
        /// </summary>
        public static string _84 {
            get {
                return ResourceManager.GetString("84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ldap Timeout.
        /// </summary>
        public static string _85 {
            get {
                return ResourceManager.GetString("85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authentication Unknown.
        /// </summary>
        public static string _86 {
            get {
                return ResourceManager.GetString("86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filter Error.
        /// </summary>
        public static string _87 {
            get {
                return ResourceManager.GetString("87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Cancelled.
        /// </summary>
        public static string _88 {
            get {
                return ResourceManager.GetString("88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parameter Error.
        /// </summary>
        public static string _89 {
            get {
                return ResourceManager.GetString("89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partial Results.
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Memory.
        /// </summary>
        public static string _90 {
            get {
                return ResourceManager.GetString("90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connect Error.
        /// </summary>
        public static string _91 {
            get {
                return ResourceManager.GetString("91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ldap Not Supported.
        /// </summary>
        public static string _92 {
            get {
                return ResourceManager.GetString("92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control Not Found.
        /// </summary>
        public static string _93 {
            get {
                return ResourceManager.GetString("93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Results Returned.
        /// </summary>
        public static string _94 {
            get {
                return ResourceManager.GetString("94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More Results To Return.
        /// </summary>
        public static string _95 {
            get {
                return ResourceManager.GetString("95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client Loop.
        /// </summary>
        public static string _96 {
            get {
                return ResourceManager.GetString("96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Referral Limit Exceeded.
        /// </summary>
        public static string _97 {
            get {
                return ResourceManager.GetString("97", resourceCulture);
            }
        }
    }
}
