//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stj.Security {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stj.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConnectionString not specified..
        /// </summary>
        internal static string MessageAdamConnectionStringNotSpecified {
            get {
                return ResourceManager.GetString("MessageAdamConnectionStringNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error converting SID to string: {0}..
        /// </summary>
        internal static string MessageAdamSIDConvertionFailed {
            get {
                return ResourceManager.GetString("MessageAdamSIDConvertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} is disabled..
        /// </summary>
        internal static string MessageAppServiceDisabled {
            get {
                return ResourceManager.GetString("MessageAppServiceDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AccessCheck failed..
        /// </summary>
        internal static string MessageAzManAccessCheckFailed {
            get {
                return ResourceManager.GetString("MessageAzManAccessCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An exception occured..
        /// </summary>
        internal static string MessageAzManAnExceptionOccured {
            get {
                return ResourceManager.GetString("MessageAzManAnExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AzMan application name not specified..
        /// </summary>
        internal static string MessageAzManApplicationNameNotSpecified {
            get {
                return ResourceManager.GetString("MessageAzManApplicationNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConnectionString not specified..
        /// </summary>
        internal static string MessageAzManConnectionStringNotSpecified {
            get {
                return ResourceManager.GetString("MessageAzManConnectionStringNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AzMan GetOperations failed..
        /// </summary>
        internal static string MessageAzManGetOperationsFailed {
            get {
                return ResourceManager.GetString("MessageAzManGetOperationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to initialize AzManHelper..
        /// </summary>
        internal static string MessageAzManHelperInitializeFailed {
            get {
                return ResourceManager.GetString("MessageAzManHelperInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot load Azman Role Policy: invalid ConnectionString {0}..
        /// </summary>
        internal static string MessageAzManInvalidConnectionString {
            get {
                return ResourceManager.GetString("MessageAzManInvalidConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} cannot be empty..
        /// </summary>
        internal static string MessageAzManParameterArrayCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessageAzManParameterArrayCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} cannot contain duplicates..
        /// </summary>
        internal static string MessageAzManParameterArrayCannotContainDuplicates {
            get {
                return ResourceManager.GetString("MessageAzManParameterArrayCannotContainDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} cannot contain commas..
        /// </summary>
        internal static string MessageAzManParameterCannotContainCommas {
            get {
                return ResourceManager.GetString("MessageAzManParameterCannotContainCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} cannot be empty..
        /// </summary>
        internal static string MessageAzManParameterIsEmpty {
            get {
                return ResourceManager.GetString("MessageAzManParameterIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} cannot exceed {1} characters..
        /// </summary>
        internal static string MessageAzManParameterTooLong {
            get {
                return ResourceManager.GetString("MessageAzManParameterTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} role already exists..
        /// </summary>
        internal static string MessageAzManRoleAlreadyExists {
            get {
                return ResourceManager.GetString("MessageAzManRoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} role does not exist..
        /// </summary>
        internal static string MessageAzManRoleDoesNotExist {
            get {
                return ResourceManager.GetString("MessageAzManRoleDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} role is not empty..
        /// </summary>
        internal static string MessageAzManRoleIsNotEmpty {
            get {
                return ResourceManager.GetString("MessageAzManRoleIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update AzMan cache failed.
        /// </summary>
        internal static string MessageAzManUpdateCacheFailed {
            get {
                return ResourceManager.GetString("MessageAzManUpdateCacheFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} user does not exist.
        /// </summary>
        internal static string MessageAzManUserDoesNotExist {
            get {
                return ResourceManager.GetString("MessageAzManUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access is denied. Security principal should be a AmxPrincipal type..
        /// </summary>
        internal static string MessagePermissionAccessDeniedInvalidPrincipal {
            get {
                return ResourceManager.GetString("MessagePermissionAccessDeniedInvalidPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access is denied. Security principal does not satisfy required operations..
        /// </summary>
        internal static string MessagePermissionAccessDeniedUserCannotAccess {
            get {
                return ResourceManager.GetString("MessagePermissionAccessDeniedUserCannotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access is denied. Security principal is not authenticated..
        /// </summary>
        internal static string MessagePermissionAccessDeniedUserNotAuthenticated {
            get {
                return ResourceManager.GetString("MessagePermissionAccessDeniedUserNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Identity found..
        /// </summary>
        internal static string MessagePolicyNoIdentityFound {
            get {
                return ResourceManager.GetString("MessagePolicyNoIdentityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RoleProvider not found..
        /// </summary>
        internal static string MessageRoleProviderNotFound {
            get {
                return ResourceManager.GetString("MessageRoleProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles feature not enabled..
        /// </summary>
        internal static string MessageRolesFeatureNotEnabled {
            get {
                return ResourceManager.GetString("MessageRolesFeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unhandled exception occured. Please check with your administrator..
        /// </summary>
        internal static string MessageUnhandledException {
            get {
                return ResourceManager.GetString("MessageUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The User is not authenticated..
        /// </summary>
        internal static string MessageUserIsNotAuthenticated {
            get {
                return ResourceManager.GetString("MessageUserIsNotAuthenticated", resourceCulture);
            }
        }
    }
}
